# Network Policy
# web-deny-all.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-deny-all
spec:
  podSelector: 
    matchLabels:
      app: web
  policyTypes:
  - Ingress
