apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubernetes.io/change-cause: kubectl set image deployment/nginx-deploy nginx=nginx:1.16.1
      --record=true
  creationTimestamp: "2021-09-06T05:22:30Z"
  generation: 8
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: default
  resourceVersion: "242885"
  uid: 41762d69-eac7-4e60-8e74-307541f790cf
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-deploy
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0 
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy
    spec:
      containers:
      - image: nginx:1.18
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-09-06T05:22:43Z"
    lastUpdateTime: "2021-09-06T05:22:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-06T05:22:30Z"
    lastUpdateTime: "2021-09-06T05:55:22Z"
    message: ReplicaSet "nginx-deploy-fbd4dcd59" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
